---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        user: "1000:1000"
        command: [ "--save", "1", "1"]

    flask-api:
        build:
            context: ./
            dockerfile: Dockerfile
        command: ["python3", "gene_api.py"]
        depends_on:
            - redis-db
        image: mihirobendre/jobs_flask_app:1.0
        ports:
            - 5000:5000

    worker:
        build: 
            context: ./
            dockerfile: Dockerfile
        command: ["python3", "worker.py"]
        depends_on:
            - redis-db
        image: mihirobendre/jobs_worker:1.0


